spring:
  datasource:
    url: jdbc:postgresql://db-joonggo-sam.cluster-cryiu6iysb91.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: testuser
    password: sam777&&&
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
