spring:
  datasource:
    url: jdbc:postgresql://51.21.118.205:5432/sam
    username: testuser
    password: sam777
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  client:
    origin: http://localhost:3000
